Added ellipsoid values to socetlinescankeywords. Fixes #5362.
DOI-USGS/ISIS3 pull request #113
Opened 2018-03-26 23:13 UTC by jessemapel

Test results can be found under `/work/projects/isis/latest/m05362_5363/test_results` there is new test data for several socetlinescankeywords app tests. It can be found in `/work/projects/isis/latest/m05362_5363/ISIS3/isis/src/socet/apps/socetlinescankeywords/tsts`.

2018-03-26 23:14 UTC, jessemapel commented
Redmine ticket [5362](https://isis.astrogeology.usgs.gov/fixit/issues/5362)

2018-03-26 23:15 UTC, jessemapel commented
DO NOT SQUASH ON MERGE.  We want to preserve the commit that has the socetframesettings changes for future work.

2018-03-26 23:23 UTC, AgoinsUSGS requested changes
Looks good, just need a some spacing added on a couple of lines and it's good to go.

2018-03-26 23:23 UTC, AgoinsUSGS commented on isis/src/socet/apps/socetlinescankeywords/socetlinescankeywords.cpp
> +  toStrm << "ECCENTRICITY     " << eccentricity <<"\n";
Need some spacing after the last << on the above 2 lines.

2018-03-26 23:25 UTC, jessemapel commented
Tests are still running, I'll put a note on here when they are finished. Previous tests of app and cat tests passed.

2018-03-28 21:21 UTC, AgoinsUSGS approved these changes

2018-04-11 15:56 UTC, makaylas commented
Did the testing finish and was it clean?

2018-04-11 21:15 UTC, jessemapel commented
Testing finished and was clean.

2018-04-12 18:43 UTC, makaylas commented
So can it be merged?

2018-04-21 18:31 UTC, merged