Updated class documentation for PvlTranslationTable
DOI-USGS/ISIS3 pull request #145
Opened 2018-04-18 21:55 UTC by jcwbacker

2018-04-19 22:23 UTC, krlberry requested changes
Found a single pre-existing misspelled word, but otherwise looks great :+1:

2018-04-19 22:23 UTC, krlberry commented on isis/src/base/objs/XmlToPvlTranslationManager/XmlToPvlTranslationManager.cpp
> +   * tranlations in the translation table. If the keyword does not
The first instance of translations in this line is misspelled as tranlations. (This existed before, but it would be great to fix it as part of this PR if possible.)

2018-04-23 23:41 UTC, jcwbacker commented on isis/src/base/objs/XmlToPvlTranslationManager/XmlToPvlTranslationManager.cpp
> +   * tranlations in the translation table. If the keyword does not
done

2018-05-01 16:39 UTC, kberryUSGS commented on isis/src/base/objs/XmlToPvlTranslationManager/XmlToPvlTranslationManager.cpp
> +   * tranlations in the translation table. If the keyword does not
:+1:

2018-05-01 16:39 UTC, krlberry approved these changes

2018-05-01 16:39 UTC, kberryUSGS commented
This is ready to be merged when dev is clean.

2018-05-02 13:27 UTC, merged