Added dark current nulling to rosvirtis2isis. Fixes #5421.
DOI-USGS/ISIS3 pull request #167
Opened 2018-05-14 19:46 UTC by jessemapel

test log results are being output at `/work/projects/isis/latest/m05421` and new test data for rosvirtis2isis is found in `/work/projects/isis/latest/m05421/new_rosvirtis2isis_test_data`

2018-05-14 19:47 UTC, jessemapel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Null the dark current scan in rosvirtis2isis.](https://trello.com/c/F4oQxKct/27-null-the-dark-current-scan-in-rosvirtis2isis)

2018-05-17 00:21 UTC, twilson271828 requested changes
Add a quick comment explaining what value is contained in frameKey[3] and what it means for future programmers looking at this code.  Other than that it looks good.

2018-05-17 18:01 UTC, jessemapel commented
Commented!

2018-05-21 19:12 UTC, twilson271828 approved these changes

2018-05-21 19:12 UTC, merged