Updated tgocassis2isis to import the output of tgocassisrdrgen
DOI-USGS/ISIS3 pull request #171
Opened 2018-05-15 22:25 UTC by kberryUSGS

2018-05-15 23:33 UTC, jcwbacker requested changes
Added a few coding style suggestions.
I will do more in-depth review tomorrow.
Also, did you add any new tests and check code coverage yet for these changes? (I didn't see any Makefile changes)

2018-05-15 23:33 UTC, jcwbacker commented on isis/src/tgo/apps/tgocassis2isis/tgocassis2isis.cpp
> +#include "IException.h"
please alphabetically order #includes

2018-05-15 23:33 UTC, jcwbacker commented on isis/src/tgo/apps/tgocassis2isis/tgocassis2isis.cpp
> +    QString transRawFile("/translations/tgoCassisInstrument.trn");
intialize with equal sign

https://isis.astrogeology.usgs.gov/documents/CodingStandards/CodingStandards.html#declaring

2018-05-15 23:33 UTC, jcwbacker commented on isis/src/tgo/apps/tgocassis2isis/tgocassis2isis.cpp
> +    } catch (IException &e) {
catch on new line
https://isis.astrogeology.usgs.gov/documents/CodingStandards/CodingStandards.html#controlStructures

2018-05-15 23:33 UTC, jcwbacker commented on isis/src/tgo/apps/tgocassis2isis/tgocassis2isis.cpp
> +  // How to tell that this is an ISIS3 exported product (generated by tgocassisrdrgen?)
i have added something to ProcessExportPds4 to address this issue (for my hyb1 ticket). You can remove this comment.

2018-05-15 23:33 UTC, jcwbacker commented on isis/src/tgo/apps/tgocassis2isis/tgocassis2isis.cpp
> +  } catch (IException &e) {
newline

2018-05-16 16:37 UTC, kberryUSGS commented
@jcwbacker Thanks! I fixed the coding-style comments you mentioned. In terms of new tests and test coverage, Makayla and I decided to just add another card to Trello for adding a new test to test these change, since it seemed like perhaps there wasn't enough cassis work for everyone to do.

2018-05-16 16:40 UTC, kberryUSGS commented
@jcwbacker Actually, never mind! We're going to add the test now.

2018-05-16 20:16 UTC, makaylas commented on isis/src/tgo/apps/tgocassis2isis/tgocassis2isis.cpp
> +  QString str;
is str just a temporary string?

2018-05-16 22:03 UTC, kberryUSGS commented on isis/src/tgo/apps/tgocassis2isis/tgocassis2isis.cpp
> +  QString str;
Yes

2018-05-16 23:10 UTC, celbal approved these changes

2018-05-16 23:10 UTC, merged