Added FileList test
DOI-USGS/ISIS3 pull request #3168
Opened 2019-03-15 23:10 UTC by paarongiroux

## Description
Added FileListTests.cpp
Implemented a constructor method into FileList.cpp that takes in an istream as a parameter to help with testing. This was declared in FileList.h but never implemented. 

## Related Issue

## Motivation and Context
Part of improving ISIS3 tests

## How Has This Been Tested?
It is a test.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2019-03-15 23:23 UTC, scsides requested changes

2019-03-15 23:23 UTC, scsides commented on isis/tests/FileListTests.cpp
> +      <<e.toString().toStdString();
White space after operators can make the code easier to read.

2019-03-16 00:45 UTC, scsides approved these changes

2019-03-16 00:45 UTC, merged

2019-03-16 00:57 UTC, Kelvinrr commented
@scsides Thanks for volunteering to  review this 👍