Changed FileName to use US English for date conversions
DOI-USGS/ISIS3 pull request #3379
Opened 2019-08-07 23:22 UTC by jessemapel

If the user is set to a non-English language, then finding the latest version of files that use short names of months fails. Now FileName always uses US English for string to date conversions.

## Description

For example, if a file uses something like 15Dec2017 and the users language is set to Spanish, then FileName cannot properly convert Dec to the 12th month because it is looking for the Spanish word for December. There is existing code in ISIS that sets these at the system level, but the QT locale utilities are not properly updating on linux (oddly this doesn't seem to be a problem on Mac). So, I added code to set the default in QT to US English and changed calls to use the default instead of the system locale.

## Related Issue

Fixes #3340 

## Motivation and Context

Users with non-English language settings had odd failures during spiceinit. See https://astrodiscuss.usgs.gov/t/spiceinit-error/171 for more info.

## How Has This Been Tested?

Tested on Mac and Linux with Cassini VIMS data because it uses kernels ranked by the date they were created.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2019-08-08 22:13 UTC, scsides requested changes
This should work. Comments on my request appreciated

2019-08-08 22:13 UTC, scsides commented on isis/src/base/objs/FileName/FileName.cpp
> +      QDate fileDate = QLocale().toDate(foundFile, fileQDatePattern);
This member was designed to work with US English locale ONLY. Would it be better to force this call to use US English, and not rely on the Application to set it correctly?

2019-08-09 16:54 UTC, scsides approved these changes

2019-08-09 17:07 UTC, jessemapel commented on isis/tests/FileListTests.cpp
> +    FAIL() << "Expected an IException\"Unable to open [FakeFile]\"";
Technically this is outside of the scope of the PR, but it's such a simple change I think it will be okay.

2019-08-09 17:09 UTC, merged