Adding GDAL into Env
DOI-USGS/ISIS3 pull request #3617
Opened 2019-12-21 00:33 UTC by Kelvinrr

## Description

This add gdal and Geos 3.6 support (necessary for GDAL because of a small API change from 3.5 to 3.6)/

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2019-12-23 20:03 UTC, krlberry requested changes
1 minor thing. The rest looks good.

2019-12-23 20:03 UTC, krlberry commented on build.groovy
>                sh 'conda env update -n isis -f environment_gcc4.yml --prune'
Doesn't this need to be changed to a `conda env create`, too, if the isis env isn't created on line 89?

2019-12-23 20:08 UTC, Kelvinrr commented on build.groovy
>                sh 'conda env update -n isis -f environment_gcc4.yml --prune'
yes, good catch. Been focusing on Mac too much.

2019-12-27 23:38 UTC, Kelvinrr commented
Should be good for re-review.

2019-12-30 15:13 UTC, krlberry approved these changes
:+1: Looks good!

2019-12-30 16:02 UTC, merged