Merge CaSSIS changes into dev.
DOI-USGS/ISIS3 pull request #375
Opened 2018-07-24 23:09 UTC by kberryUSGS

2018-07-26 23:03 UTC, celbal requested changes
So git is not correctly reflecting your changes. It's thinking that all of the IPCE changes are conflicts and that we changed a lot of files that we didn't.

I suggest that you make a new branch and copy the files that were changed rather than trying to deal with all of these problems.

2018-07-26 23:03 UTC, makaylas commented on isis/src/control/apps/cnetwinnow/cnetwinnow.cpp
> +    //Check to see if the network has split
Can we remove this commented out code?

2018-07-26 23:03 UTC, makaylas commented on isis/src/control/objs/ControlCubeGraphNode/ControlCubeGraphNode.cpp
> +#include "IsisDebug.h"
Wasn't this object deleted?

2018-07-26 23:03 UTC, makaylas commented on isis/src/control/objs/ControlCubeGraphNode/ControlCubeGraphNode.h
> +#ifndef ControlCubeGraphNode_h
Wasn't this deleted?

2018-07-26 23:03 UTC, makaylas commented on isis/src/control/objs/ControlMeasure/ControlMeasure.cpp
>  #include "ControlMeasureLogData.h"
ControlCubeGraphNode was deleted

2018-07-26 23:03 UTC, makaylas commented on isis/src/control/objs/ControlMeasure/ControlMeasure.h
> +  class ControlCubeGraphNode;
ControlCubeGraphNode was deleted

2018-07-26 23:03 UTC, makaylas commented on isis/src/control/objs/ControlNet/ControlNet.h
> + *   http://www.usgs.gov/privacy.html.
I think you need to merge in the IPCE changes

2018-07-26 23:03 UTC, makaylas commented on isis/src/hayabusa/apps/amica2isis/amica2isis.cpp
>    // Create a PVL to store the translated labels in
You need a history comment in amica2isis.xml

2018-07-26 23:03 UTC, makaylas commented on isis/src/hayabusa/apps/hyb1pds4gen/hyb1pds4gen.cpp
> +#include "Isis.h"
Does the naming convention of this app follow the ISIS standards for naming conventions?

2018-07-26 23:03 UTC, makaylas commented on isis/src/qisis/apps/ipce/IpceMainWindow.h
>   */
I think you need to merge in the IPCE changes

2018-07-26 23:03 UTC, makaylas commented on isis/src/qisis/objs/CnetEditorWidget/APrioriLatitudeFilter.cpp
>  #include "APrioriLatitudeFilter.h"
Should this be Apriori rather than APriori?

2018-07-27 22:29 UTC, krlberry commented
@makaylas :+1: Thank you, you're right about this missing the ipce changes.

2018-08-14 14:49 UTC, kberryUSGS commented
See Jeannie's PR #399

2018-08-14 14:49 UTC, closed without merging