Moved MGS data into source
DOI-USGS/ISIS3 pull request #3754
Opened 2020-03-12 22:17 UTC by kaitlyndlee

## Description

Moved translation, and serial numbers into src code so that they are versioned. Updated moc2isis to grab translation files from $ISISROOT. Updated ShapeModelFactory's unit test to remove the references to $ISIS3DATA.

## Related Issue

#3727 

## Motivation and Context

This change is a part of moving the isis3data area, some files going into the source code.

## How Has This Been Tested?

Ran all mgs tests. mocproc is failing, possibly due to spiceinit. All other tests pass.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2020-03-12 23:21 UTC, scsides requested changes
Just the one fix and this looks good to go

2020-03-12 23:21 UTC, scsides commented on isis/src/base/objs/ShapeModelFactory/ShapeModelFactory.truth
> +**I/O ERROR** Invalid shape model file [/usgs/cpkgs/isis3/isis_data/mgs/testData/ab102401.cub] in Kernels group.
These line contain full paths "/usgs/cpkgs". There should be a regex in the unit test that is removing these so the tests will run with the data being in this and only this path.

2020-03-13 22:34 UTC, kberryUSGS commented
Looks like this test passed on Jenkins: https://astroservices.usgs.gov/jenkins/job/USGS-Astrogeology/job/ISIS3/view/change-requests/job/PR-3754/5/execution/node/113/log/?consoleFull (control-f #253:)

2020-03-13 23:34 UTC, scsides approved these changes

2020-03-13 23:34 UTC, merged