Reformatted slpmap documentation
DOI-USGS/ISIS3 pull request #3809
Opened 2020-03-27 18:21 UTC by kaitlyndlee

## Description

The way slpmap's documentation was formatted was not clear about the use of the PIXRES parameter. In order to make the use of the parameter more clear, we moved around a few paragraphs and highlighted a few points. Also fixed a few typos.

## Related Issue

https://github.com/USGS-Astrogeology/ISIS3/issues/3562

## Motivation and Context

Clear up confusions about PIXRES parameter.

## How Has This Been Tested?

Generated docs and viewed them in a web browser.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2020-03-27 21:53 UTC, Kelvinrr reviewed
It looks well enough to me but I'd rather get a review from someone who knows more about this application. @scsides @jessemapel @kberryUSGS?

2020-03-30 15:48 UTC, krlberry requested changes
I think I found a single typo, but other than that, looks good to me!

2020-03-30 15:48 UTC, kberryUSGS commented on isis/src/base/apps/slpmap/slpmap.xml
> +      equal to the y distance form top to bottom of the pixel.
typo: form -> from

2020-03-30 16:07 UTC, jessemapel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Enable slpmap to accept cubes made with elevation instead of only radius information](https://trello.com/c/wMl5PtOv/86-enable-slpmap-to-accept-cubes-made-with-elevation-instead-of-only-radius-information)

2020-03-30 16:40 UTC, jessemapel reviewed
This looks good pending Kristin's typo fix. It would be nice to re-do this using latex and properly defining kernel matrices, but that's beyond the scope of this PR>

2020-03-30 17:58 UTC, krlberry approved these changes
:+1: I forgot that I could just quickly fix the typo I found myself.

2020-03-30 18:20 UTC, merged