Moves save/restore/delete of Stretch from AdvancedStretchTool to StretchTool.
DOI-USGS/ISIS3 pull request #3965
Opened 2020-08-04 19:01 UTC by kberryUSGS

##  Description
Moves save/restore/delete of Stretch from AdvancedStretchTool to StretchTool.
The buttons in AdvancedStretchTool still function as previously, but under the hood just signal the same functions as the buttons in the base StretchTool. 

## Related Issue
StretchTool refactor, no issue. Also PRing into a feature branch, not dev.

## Motivation and Context

## How Has This Been Tested?
Tested by hand. 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2020-08-04 19:02 UTC, kberryUSGS commented on isis/src/qisis/objs/StretchTool/StretchTool.cpp
> +    // Save/Restore strech only supported for Grayscale images. Hide buttons if in RGB.
I'm omitting the change suggested in this comment, because I'm working on adding RGB now.

2020-08-04 23:54 UTC, scsides requested changes
Minor comment suggestion

2020-08-04 23:54 UTC, scsides commented on isis/src/qisis/objs/StretchTool/StretchTool.cpp
> +    // Buttons migrated out of Advanced Stretch Tool
This will not make sense to a programmer in a few days

2020-08-06 14:16 UTC, scsides approved these changes

2020-08-06 14:16 UTC, merged