FindImageOverlaps test
DOI-USGS/ISIS3 pull request #4007
Opened 2020-09-09 00:59 UTC by acpaquette

Adds a new gtest for the findimageoverlaps application.

## Description
Adds a new gtest for the findimageoverlaps function that adds footprint polygons to a set of cubes, applies the findimageoverlaps function and checks the return values.

## Related Issue
None (Remake of an old PR that was clobbered #3836)

## Motivation and Context
This is another application that needs to be converted to a suite of gtests at some point.

## How Has This Been Tested?
This is a test

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [AUTHORS.rst](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/AUTHORS.rst) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2020-09-10 17:15 UTC, Kelvinrr reviewed
Looks pretty clean, the only thing is make sure the old Make test is deleted for default tests. 

Also, this is still missing the "full overlap" test from the original Make tests so we can't check this off completely yet. If you don't think you have time to get to that today, I'm cool with merging and taking care of it since I'm not sure I have enough for today.

2020-09-10 18:15 UTC, Kelvinrr requested changes
Fixtures.cpp seems to have build errors on CentOS.

2020-09-11 19:03 UTC, Kelvinrr approved these changes, later dismissed
Think this is good to go after CI finishes.

2020-09-11 19:03 UTC, Kelvinrr commented on isis/tests/FuntionalTestsFindImageOverlaps.cpp
> +  pvl.addObject(polyObject);
I have a passing thought that putting this boilerplate into a function is a good idea, but with the new fixture I'm not sure we will be doing this super often going forward anyways.

2020-09-11 20:06 UTC, jlaura commented
@acpaquette Looks like this needs a rebase? Because of the stats work.

2020-09-11 21:15 UTC, acpaquette commented on isis/tests/FuntionalTestsFindImageOverlaps.cpp
> +  pvl.addObject(polyObject);
That's something I was considering but I don't know how worth while it is like you mention.

2020-09-11 21:20 UTC, Kelvinrr approved these changes

2020-09-11 21:21 UTC, merged