Added hyb2onccal GTests
DOI-USGS/ISIS3 pull request #4037
Opened 2020-09-25 22:55 UTC by kaitlyndlee

## Description

Added GTests for ONC-T images and removed old Makefile tests. Added two fixtures to test a cropped and non-cropped Hayabusa ONC-T image.  There was also a typo in the instrument group translation file that set the SpacecraftClockEndCount to SpacecraftClockStartCount.

## Related Issue

No issue.

## Motivation and Context

Part of the test conversion.

## How Has This Been Tested?

GTests pass.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2020-09-28 23:34 UTC, scsides requested changes
Just the one needed fix

2020-09-28 23:34 UTC, scsides commented on isis/src/hayabusa2/apps/hyb2onccal/Hyb2OncCalUtils.h
> +      if (IsSpecial(imageIn[i])) {
Suggest pulling the divide out of the loop and putting below, so all of the smear is divided by the same number.

2020-09-30 01:49 UTC, scsides approved these changes

2020-09-30 16:02 UTC, Kelvinrr approved these changes

2020-09-30 22:03 UTC, merged