pds2isis gtest
DOI-USGS/ISIS3 pull request #4144
Opened 2020-11-24 21:18 UTC by tgiroux

## Description

Convert Makefile tests to gtest for pds2isis.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2020-11-24 23:29 UTC, AustinSanders requested changes
It might be worth testing the DNs with the .cub's hist object.  We usually just test mean, sum, stddev, and valid pixels.

2020-11-30 15:58 UTC, AustinSanders submitted a review, later dismissed

2020-12-02 00:06 UTC, AustinSanders requested changes
Looks like there's a failing test on Mac

1845 - Pds2Isis.Pds2isisTestBandBin (Failed)

2020-12-03 16:16 UTC, acpaquette commented on isis/tests/FunctionalTestsPds2isis.cpp
> +  QString cubeFileName = "/home/tgiroux/Desktop/pds2isis_bandbin_out.cub";
Missed removing a local path, which caused the failure

2020-12-04 16:12 UTC, AustinSanders approved these changes

2020-12-07 01:37 UTC, merged