Update Camera.cpp to fix local norm for pushbroom cameras (old PR#4214)
DOI-USGS/ISIS3 pull request #4340
Opened 2021-03-04 22:53 UTC by victoronline

Originally the fix was submitted via PR [#4214](https://github.com/USGS-Astrogeology/ISIS3/pull/4214) for branch 3.10.2 but since that branch is no longer active, changes will be submitted to dev.

Although this does fix this function when phocube uses it with integer sample/line values, it does not fix it when other applications use non-integer sample/line values.  A new issue has been created [#4256](https://github.com/USGS-Astrogeology/ISIS3/issues/4256) to address what we believe to be a fix for the other cases.

## Description
Currently, the DBL_MIN is not operating as expected. The functionality that is intended is:
Calculate normal by grabbing elevation values at the edges of the pixel in question.

What is actually happening:
The values gathered are still not from the same pixel. It appears as though the DBL_MIN is not subtracting more than the rounding error, and this is essentially returning the same value as if the code was:

      QList< QPair< double, double > > surroundingPoints;
      surroundingPoints.append(qMakePair(samp, line - 0.5));
      surroundingPoints.append(qMakePair(samp, line + 0.5));
      surroundingPoints.append(qMakePair(samp - 0.5, line));
      surroundingPoints.append(qMakePair(samp + 0.5, line));

This change was made to version 3.10.2 originally but is not being submitted to dev branch.

## Motivation and Context
This is detrimental when calculating photometric angles for push-broom and push-frame cameras because 1.0 could be the pixel center, 0.5 is the edge of pixel 1, but 1.5 is the edge of pixel 2. This does not work well when a push-broom imager is flying in a reverse direction, or for frame boundaries of a push-frame camera. The calculation is using a completely wrong location on the body.

## How Has This Been Tested?
The LROC team has tested the fix. Will provide details in the comments below but a test (GTest) has not been created for this yet.

## Screenshots (if appropriate):
Please see the issue. Several screenshots and examples have been included.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [X] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user-impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [X] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2021-03-04 23:01 UTC, scsides approved these changes

2021-03-04 23:04 UTC, scsides requested changes
woops missed the camera.h history comment

2021-03-09 20:42 UTC, victoronline reviewed
Good catch. Thanks! Updated header file with comments

2021-03-10 18:39 UTC, scsides approved these changes

2021-03-10 18:41 UTC, merged

2021-08-04 22:07 UTC, victoronline commented
Have a question. I see this was merged but has this been included in any releases? I don't see it in the changelog anywhere.

2021-08-04 23:38 UTC, scsides commented
Victor,

It made it into 5.0 and up.

Stuart

________________________________
From: Victor Silva ***@***.***>
Sent: Wednesday, August 4, 2021 3:07 PM
To: USGS-Astrogeology/ISIS3 ***@***.***>
Cc: Sides, Stuart C ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [USGS-Astrogeology/ISIS3] Update Camera.cpp to fix local norm for pushbroom cameras (old PR#4214) (#4340)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Have a question. I see this was merged but has this been included in any releases? I don't see it in the changelog anywhere.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSGS-Astrogeology%2FISIS3%2Fpull%2F4340%23issuecomment-893006730&data=04%7C01%7Cssides%40usgs.gov%7C58f2b86908c94aef247508d9579449b6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637637116675488342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VYYF9gQU4xX8cudFCcGhvknYUMYW1X626MYPEYOzAHQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC25ETPF5BYAZLKAZKE6FYTT3G2ZVANCNFSM4YUEEX6A&data=04%7C01%7Cssides%40usgs.gov%7C58f2b86908c94aef247508d9579449b6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637637116675488342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jjIekv1Gu%2Fey0a%2Bu6jcAxVKUrG0fabpGcZr2cpP9qiQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cssides%40usgs.gov%7C58f2b86908c94aef247508d9579449b6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637637116675498296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zlHaPMUjjLl1iqdmlO5srpOtIAeWY%2Be9vWibb0GGxZE%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cssides%40usgs.gov%7C58f2b86908c94aef247508d9579449b6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637637116675508253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5gYPkfwOuROzR6vggHjif7m%2FtknaAM%2FxNZBvQ%2F7%2FKiw%3D&reserved=0>.