Normalized test names and file names
DOI-USGS/ISIS3 pull request #4366
Opened 2021-03-15 22:38 UTC by AustinSanders

Changes the file and test names to better match the guidelines described [here](https://github.com/USGS-Astrogeology/ISIS3/wiki/Writing-ISIS3-Tests-Using-Gtest-and-Ctest#app-conversion--gtest-pr-checklist)

## Description

## Related Issue
#4206 

## Motivation and Context
Test names should be consistent

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2021-03-16 00:18 UTC, scsides requested changes
What criteria are these names. The camel case was readable, every word/, I'm not sure the new lower case is.

2021-03-16 00:18 UTC, scsides commented on isis/tests/FunctionalTestsCamdev.cpp
> +TEST_F(LineScannerCube, FunctionalTestCamDevDefault) {
If I'm following the normalization, shouldn't this be "FunctionalTestCamdevDefault" ?

2021-03-16 00:18 UTC, scsides commented on isis/tests/FunctionalTestsMoccal.cpp
> +TEST_F(MgsMocCube, FunctionalTestMromoccalDefault) {
Not sure how this got through the first time. "moccal" is an MGS app not an MRO. On the other hand, the app name is "moccal" not "mgsmoccal", shouldn't this just be "FunctionalTestMoccalDefault" ?

2021-03-16 00:18 UTC, scsides commented on isis/tests/FunctionalTestsMoccal.cpp
> +TEST_F(MgsMocCube, FunctionalTestMromoccalIofFalse) {
ditto

2021-03-16 00:18 UTC, scsides commented on isis/tests/FunctionalTestsMoccal.cpp
> +TEST_F(MgsMocCube, FunctionalTestMromoccalNullwagoTrue) {
ditto

2021-03-16 00:18 UTC, scsides commented on isis/tests/FunctionalTestsMoccal.cpp
> +TEST_F(MgsMocCube, FunctionalTestMromoccalCameraComparison) {
ditto

2021-03-16 15:18 UTC, Kelvinrr reviewed
Other than the ones Stuart found, I couldn't find other inconsistencies.

2021-03-22 19:48 UTC, Kelvinrr commented
@scsides Does this look good to go?

2021-03-22 20:05 UTC, scsides approved these changes

2021-03-22 21:24 UTC, merged