Fix caminfo uselabel SegFault
DOI-USGS/ISIS3 pull request #4402
Opened 2021-04-15 20:27 UTC by tgiroux

## Description

In caminfo there is a call to BandGeometry::collect that closes the input cube object if uselabel=yes. The cube needs to remain open for a few other tasks, so this was causing a segmentation fault. To fix this, I added a few lines after the BandGeometry::collect call that open the cube back up if uselabel=yes.

## Related Issue

#4401 

## Motivation and Context

This bug was found in the release candidate due at end of month.

## How Has This Been Tested?

All caminfo gtests are passing. Both sample caminfo calls given in #4401 run correctly.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2021-04-16 18:59 UTC, acpaquette requested changes
It would be better to remove the `cube.close()` from the CamTools `BandGeometry::collect` function. This was something that was incorrectly added when Blob reading was updated.

2021-04-16 19:32 UTC, scsides requested changes, later dismissed

2021-04-16 19:32 UTC, scsides commented on isis/src/base/apps/caminfo/caminfo.cpp
> +          // When getFootBlob is true, incube is closed in the above function call
I'm not sure why the collect call above closes a cube that was passed in to it. Seems like a better solution would be to remove the close inside collect() and then close it in at the bottom of this function caminfo(cube, ui) or let what ever code opened it do the closing (i.e., caminfo(ui)).

2021-04-22 16:33 UTC, jessemapel approved these changes

2021-04-22 18:51 UTC, acpaquette approved these changes

2021-04-22 18:51 UTC, merged