Updates to PDS4 branch
DOI-USGS/ISIS3 pull request #4505
Opened 2021-06-03 16:28 UTC by kberryUSGS

## Description
Adds: 
* isisimport, a generalized input application which currently supports pds4 input and a template to import tgo cassis images.
* Support for tgo casssis labels and the ability to look up the template to use for export to isisexport
* 
Renames:
* topds4 to isisexport

## Related Issue
ISIS PDS4 work

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2021-06-03 17:05 UTC, amystamile-usgs reviewed
Added a few questions.

2021-06-03 17:05 UTC, amystamile-usgs commented on isis/src/base/apps/isisexport/isisexport.h
> +extern QString PDS4PixelType(Isis::PixelType ipixelType, Isis::ByteOrder ibyteOrder);
Should this be in the header? Just from doing app conversions, I noticed that the function prototypes are still in the apps cpp file rather than in the header. Not sure if we should be consistent with the other apps.

2021-06-03 17:05 UTC, amystamile-usgs commented on isis/src/base/apps/isisimport/isisimport.xml
> +    Convert from PDS 4 format (other formats will be supported in the future) using template XML files to an ISIS Cube.
Should we standardize this and remove any mention of PDS 4 similar to changes in isisexport.xml?

2021-06-03 17:05 UTC, amystamile-usgs commented on isis/tests/FunctionalTestsIsisImport.cpp
> +TEST_F(TempTestingFiles, FunctionalTestIsisImportLabelXmlInput) {
Not sure if we should keep the naming consistent with `FunctionalTestIsisexport`. So instead naming the tests `FunctionalTestIsisimport`. Same goes for the naming of the file.

2021-06-03 17:14 UTC, tgiroux commented on isis/tests/FunctionalTestsIsisexport.cpp
> +TEST_F(SmallCube, FunctionalTestIsisexport4NoOriginalLabel) {
Should be FunctionalTestIsisexportNoOriginalLabel

2021-06-03 23:00 UTC, scsides commented on isis/src/base/apps/isisimport/isisimport.xml
> +    Convert from PDS 4 format (other formats will be supported in the future) using template XML files to an ISIS Cube.
Yes

2021-06-03 23:01 UTC, scsides commented on isis/src/base/apps/isisexport/isisexport.h
> +extern QString PDS4PixelType(Isis::PixelType ipixelType, Isis::ByteOrder ibyteOrder);
We should be consistent

2021-06-03 23:03 UTC, scsides requested changes
We should make the suggested changes before merging.

2021-06-04 03:15 UTC, jessemapel commented
I looked at this again and I'm concerned about the topds4 name change. We put out topds4 in [5.0.0](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md#added) which means changing the name of the application is breaking. Is there someway we can provide a symlink in the bin directory for backwards compatibility? I don't think anyone used it yet, so maybe this is much ado about nothing.

2021-06-04 16:33 UTC, kberryUSGS commented
@jessemapel I'm not how to get a symlink to set up to `isisexport` from `topds4` in the build system. I agree that it's technically a breaking change, and also that it's unlikely that `topds4` is already being used. This is just a thought, but could it be possible to classify (somehow) apps as "in beta" and  if they are "in beta" then we're allowed to make breaking changes to them without needing to increment the ISIS version number? It seems like one possible way to have the flexibility to distribute apps that are still in development and might have major changes made to them, including API-breaking ones, but to get them available for testing in the community.

2021-06-04 16:34 UTC, scsides commented
I agree with the name change problem, but I also believe sooner is better than later is appropriate here. I don't know of a reasonable way to add a link.

2021-06-07 13:05 UTC, scsides approved these changes, later dismissed

2021-06-07 18:57 UTC, jessemapel approved these changes, later dismissed
6.0 tick looks good. I updated the CHANGELOG as we don't pull a new header until the release is frozen.

2021-07-07 17:38 UTC, scsides approved these changes, later dismissed

2021-07-27 23:20 UTC, scsides approved these changes
The most recent Jenkins build doesn't have any related failures.

2021-07-27 23:20 UTC, merged