Added the ability to update CSM model state in jigsaw
DOI-USGS/ISIS3 pull request #4529
Opened 2021-06-15 23:10 UTC by jessemapel

## Description

Adds the ability to write updated CSM model states to cubes in jigsaw.

## Related Issue

#4410 

## Motivation and Context

This allows us to store the updated model state from jigsaw for use in future applications or for export to other SETs such as Socet GXP.

## How Has This Been Tested?

Tested locally on CTX test data set. The updated BLOB is on the cube with the jigged comment. Inspected USGSCSM state string JSON and it contained the updated parameters. Pre and post runs of campt on images also showed updates consistent with the results of the jigsaw solution.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2021-06-15 23:14 UTC, jessemapel commented on isis/src/control/objs/BundleAdjust/BundleAdjust.cpp
> +    CSMCamera *csmCamera = dynamic_cast<CSMCamera*>(imageCam);
I am not happy about having the dynamic_cast in BundleAdjust and not using the Observation, but attempts to use the polymorphism of the observation resulting in strange issues with the indices in the control network not matching the indices in the observations. I also ran into issues with who has the correct camera model and simultaneous open/close of the cube. This approach side-steps all of those issues at the cost of the cast happening here.

2021-06-16 17:00 UTC, kberryUSGS approved these changes
This all looks good to me!

2021-06-17 19:11 UTC, kberryUSGS commented on isis/tests/FunctionalTestsJigsaw.cpp
> +TEST_F(CSMNetwork, unctionalTestJigsawCSM) {
Could you put the 'F' back in?

2021-06-17 19:12 UTC, kberryUSGS requested changes
One character typo! Then I'll go back to approving the PR.

2021-06-17 19:23 UTC, kberryUSGS approved these changes

2021-06-17 19:24 UTC, merged