Merges BundleXYZ into dev
DOI-USGS/ISIS3 pull request #495
Opened 2018-10-23 18:08 UTC by jessemapel

This is a large feature branch and has a lot of test data that needs to be checked in once this is merged. This also needs to be squashed down prior to merging so that it can be reverted in case of an emergency.

2018-10-23 18:16 UTC, jessemapel commented
Closes #455

2018-10-31 19:43 UTC, SgStapleton requested changes

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/control/apps/jigsaw/jigsaw.cpp
> +    coord3Sigma = ui.GetDouble("POINT_Z_SIGMA");
POINT_X/Y/Z_SIGMA will always overwrite POINT_LATITUDE/LONGITUDE/RADIUS_SIGMA values? Are these both allowed to be set in the gui?

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/control/objs/BundleResults/BundleResults.cpp
> +  // }
Was this meant to be removed, or are we leaving this in for the time being?

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/control/objs/BundleAdjust/BundleAdjust.h
> +   *   @history 2011-07-12 Ken Edmundson - Segmentation fault bugfix in OutputHeadsolveCholesker method.
I imagine this was an accident as the method was never altered...?

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/control/objs/BundleResults/unitTest.cpp
> +    // }
Does this need to stay?

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/control/objs/BundleSolutionInfo/BundleSolutionInfo.h
> +      FileName        *m_inputControlNetFileName;     //!< Input control network file name
```suggestion
      FileName            *m_inputControlNetFileName;     //!< Input control network file name
```

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/control/objs/BundleUtilities/BundleControlPoint.cpp
> +    // *** TODO *** Why is the cholmodQMatrix not copied? Ask Ken
Was this ever decided? (May be irrelevant...?)

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/control/objs/ControlPoint/ControlPoint.cpp
> +    // }
Would this technically have been tested fully at this point?

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/control/objs/ControlPoint/ControlPoint.h
>  //      ZConstrained = 5;
Should these all be cleaned up?

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/control/objs/ControlPoint/ControlPoint.h
> +//      SurfacePoint::CoordinateType coordType;
This not needed?

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/qisis/objs/ConcurrentControlNetReader/ConcurrentControlNetReader.h
> +  *                         networks. Fixes #5068.
```suggestion
   *                         networks. Fixes #5068.
```

2018-10-31 19:43 UTC, SgStapleton commented on isis/src/qisis/objs/WindowTool/WindowTool.cpp
> +     position.setX(position.x() + window->width());
```suggestion
      position.setX(position.x() + window->width());
```

2018-10-31 19:52 UTC, jessemapel commented on isis/src/control/apps/jigsaw/jigsaw.cpp
> +    coord3Sigma = ui.GetDouble("POINT_Z_SIGMA");
The two sets of sigmas are mutually exclusive. If you look at `CONTROL_POINT_COORDINATE_TYPE_BUNDLE` it either excludes lat/lon/rad or x/y/z

2018-10-31 22:14 UTC, SgStapleton approved these changes

2018-10-31 22:15 UTC, SgStapleton commented
Everything looks good!

2018-10-31 22:15 UTC, merged