hist blob fix
DOI-USGS/ISIS3 pull request #4995
Opened 2022-07-14 21:10 UTC by gsn9

There was an error with the history blobs on a cube, if the keyword `from` in the blob contained a `,` the application would throw an error.

## Description

Changed the PvlKeyword parser to handle keywords that contain a `,`.

## Related Issue
Solves #4337 

## Motivation and Context

## How Has This Been Tested?

Tested locally to verify that running an application like cathist on a cube that has a key with `1,2,3` in its value doesn't error out and the history is correctly displayed. 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2022-07-14 21:38 UTC, Kelvinrr requested changes

2022-07-14 21:38 UTC, Kelvinrr commented on isis/src/base/objs/PvlKeyword/PvlKeyword.cpp
> +    QRegularExpressionMatch match = regex.match(temp);
What is the regex trying to do here? If you are looking for an arbitrary list of leftover band numbers, something like `(,*[0-9]+)+` would probably be better. This looks more like it's just checking for a comma which is basically the same as `keyword[0] == ','`

2022-07-14 22:41 UTC, Kelvinrr commented on isis/src/base/objs/PvlKeyword/PvlKeyword.cpp
> +    QRegularExpressionMatch match = regex.match(temp);
why not just pass in the string directly into the match func and not use a temp var?

2022-07-15 16:43 UTC, Kelvinrr commented
If we can get a receipt showing local tests are reasonably clean, we can merge this.

2022-11-30 20:01 UTC, amystamile-usgs commented
Seems like the regex `(,*[0-9]?)?` was not properly matching with the first comma in the keyword. I updated to only look at the first character for a comma by using `^,`

<img width="933" alt="Screen Shot 2022-11-30 at 12 58 09 PM" src="https://user-images.githubusercontent.com/74275278/204896389-cb38c971-a84c-44c4-8b47-4b162db1fb64.png">

2022-12-01 16:41 UTC, amystamile-usgs commented
Jenkins tests look good https://jenkins.prod-asc.chs.usgs.gov:8443/job/ISIS/view/change-requests/job/PR-4995/. This is ready for a re-review.

2022-12-01 17:41 UTC, AustinSanders approved these changes

2022-12-01 18:47 UTC, Kelvinrr approved these changes

2022-12-01 18:48 UTC, merged