Minimize Cache by Default
DOI-USGS/ISIS3 pull request #5297
Opened 2023-09-19 23:08 UTC by acpaquette

## Description
Change spice rotation m_minimizeCache default to Yes, enforcing all SpiceRotation objects to minimize the cache unless manually turned off.

## Related Issue

## How Has This Been Validated?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2023-11-20 19:09 UTC, chkim-usgs approved these changes
Looks good. Just wondering if there was something that prompted this PR (like an issue or a discussion that we could reference)?

2024-03-13 18:04 UTC, amystamile-usgs commented
@acpaquette has this not been merged because it's API breaking?

2024-03-19 16:10 UTC, acpaquette commented
@amystamile-usgs More or less, it also may have further reaching implications that need to be looked at

2024-11-13 16:51 UTC, amystamile-usgs commented
@acpaquette can this be rebased with dev so we can check tests before merging into 9.0 release?

2024-11-18 17:57 UTC, amystamile-usgs commented
The following tests are failing:

	814 - apollopaninit_app_test_default (Failed)
	902 - juno_module_test_junocam (Failed)
	1005 - hideal2pds_app_test_croppedAlphaCube (Failed)
	1006 - hideal2pds_app_test_differentBitCompressions (Failed)
	1041 - near_module_test_msi (Failed)

2024-11-18 17:58 UTC, amystamile-usgs requested changes
Fix test failures

2025-11-14 15:04 UTC, closed without merging