App to callable function conversion rough draft
DOI-USGS/ISIS3 pull request #530
Opened 2018-11-07 20:47 UTC by Kelvinrr

The design, or lack thereof, isn't supposed to be a suggestion of how to go about it. This is obviously very rough but hopefully good for evaluating how tangible the problem is and for serving as a starting point for discussing a concrete implementation. 

Some questions to consider with my thoughts (obviously, try to disagree): 
 * Isis typically keeps apps and lib code partitioned. Obviously any way we approach this will end with that partition coming down or at least becoming much softer. Where should app function code be placed so that we don't add technical debt? I would argue colocating the functions in the app directories and changing CMake to include these funcs into the library, where the app wrappers go hardly matters since they are super thin and have no dependencies other than the func being callable from isislib. 
 * Global variables are a problem (because of a `Process` classes and how possible function signatures are fixed) so we need a clean way to handle these variables. My argument: try to make the `Process` classes more flexible in their acceptable function signatures, if that is not possible, namespace the functions/params.
*  In this example, the input param is the same for all functions (`std::vector<char*>`), but it makes the interface messier for the user as functions will require Isis params inputed as a vector of c strings ( `"from=something.cub"`, `"to=out.cub"`, etc.). Is this acceptable? Is there a cleaner way? Maybe by changing `UserInterface` we can get nicer interfaces for the callable functions.

2018-11-07 21:03 UTC, kberryUSGS commented on isis/src/base/objs/Apps/Apps.truth
> +who cares
Nice truthdata :+1:

2018-11-15 19:40 UTC, Kelvinrr commented on isis/src/base/apps/crop/crop.cpp
> +    }
ProccessByLine/Brick can use lambdas with captures, this means the functions can be defined within the app func while capturing the required additional values as long as they are defined in the scope of the function. This avoids multiple packing/unpacking from using a UI object (which doesn't support arbitrary types) or void* array.

2018-11-15 19:59 UTC, jessemapel commented on isis/src/base/apps/crop/crop.cpp
> +    }
That sounds good to me

2018-11-16 21:30 UTC, Kelvinrr commented
All mains of apps are located in a file named `main.cpp` located in any particular app folder.

2018-11-16 21:33 UTC, Kelvinrr commented on isis/cmake/AddIsisModule.cmake
> +  list(REMOVE_ITEM sources "${folder}/main.cpp")
This makes sure main is not added to the library.

2018-11-16 21:36 UTC, Kelvinrr commented on isis/src/base/apps/ckwriter/CkKernelWriter.cpp
> +#include "CkSpiceSegment.h"
The SpiceSegment class was separated into two different classes. Might quickly look into merging the two if possible.

2018-11-16 21:38 UTC, Kelvinrr commented on isis/src/hayabusa/apps/amica2isis/AmicaImportFits.cpp
> +#include "AmicaImportFits.h"
ImportFits was mostly duplicated between Amica and Nirs but there is a logicblock that is different. Need to consolidate the two and move into the ISIS3 lib.

2018-11-16 21:39 UTC, Kelvinrr commented on isis/src/lro/apps/lrowacpho/Exponential.cpp
> +        if ((band <= 0) || (band > (int) m_bandpho.size())) {
Merged Photometery classes, only difference was naming conventions.

2018-11-16 21:44 UTC, Kelvinrr commented on isis/src/mgs/apps/mocuncompress/main.cpp
> +void decodeLoad(char *decodefile)
Stuffed some floating functions in the app folder into main as they were only being used here.

2018-11-16 21:44 UTC, Kelvinrr commented on isis/src/mro/apps/hi2isis/main.cpp
> +void SaveHiriseAncillaryData(ProcessImportPds &process, Cube *ocube) {
Was originally floating in another .cpp file, only used in main so moved in to main.

2018-11-16 22:19 UTC, kberryUSGS commented
@Kelvinrr Could you update this with a new description? It doesn't need to go into a lot of detail, I'm interested in a brief overview, if possible.

2018-11-16 22:31 UTC, krlberry requested changes
For some very straightforward pre-meeting feedback: 
`isis/src/mro/.DS_Store` and `isis/src/mro/apps/.DS_Store` should be removed from this PR.

2018-11-19 17:16 UTC, Kelvinrr commented on isis/src/base/apps/crop/crop_func.cpp
> -#include "Isis.h"
rename to crop.cpp

2018-11-19 17:22 UTC, Kelvinrr commented on isis/src/base/objs/ProcessByBrick/ProcessByBrick.cpp
> +  void ProcessByBrick::StartProcess(std::function<void(Buffer &in)> funct ) {
Do this for in/out version too

2018-11-19 17:25 UTC, Kelvinrr commented on isis/src/lro/apps/lrowacpho/HapkeExponential.cpp
> +//        m_ * m______  = A1 exp(B1 phase) + A2 ( µ0 + µ )exp(B2 phase) + A3 ( µ0 + µ ) + A4
delete the m's

2018-11-19 17:29 UTC, Kelvinrr commented on isis/src/mgs/apps/mocuncompress/getdecode.h
> +// extern uint8 code[], left[], right[];
Delete this file, make sure to re-test mocuncompress

2018-11-19 17:40 UTC, Kelvinrr commented
Double check ZeroDark

2018-11-20 21:02 UTC, krlberry approved these changes

2018-11-20 21:03 UTC, merged

2018-11-20 21:41 UTC, jlaura commented
@scsides Can you comment on this PR please.

2018-11-21 00:11 UTC, scsides commented
@jlaura will add comments to issue #600