Move banner jpg out of repo to S3, not in public domain
DOI-USGS/ISIS3 pull request #5680
Opened 2024-11-23 05:24 UTC by jrcain-usgs

The new Europa Clipper Image on the banner looks like it's from [here](https://www.jpl.nasa.gov/images/pia26068-europa-clipper-artists-concept/) or [here](https://photojournal.jpl.nasa.gov/catalog/PIA26068).  Those sources are subject to the JPL Image Use Policy.  Though that policy is very permissive, it does not confirm that this image is in the public domain.  I moved it into the asc-docs S3 bucket and linked to it there, so our banner will remain the same, but our repo won't have non-public-domain images.

## Description

## Related Issue

## How Has This Been Validated?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2024-11-25 18:59 UTC, Kelvinrr requested changes

2024-11-25 18:59 UTC, Kelvinrr commented on isis/src/docsys/build/main.xsl
> +                  is moving to <a href="https://astrogeology.usgs.gov/docs/" target="_blank">USGS Astrogeology Software Docs</a>.
"Some ISIS Docs Have Moved" I think is a good change, but this new paragraph is less clear than the original. I would suggest reverting it.

2024-11-25 19:46 UTC, jrcain-usgs commented on isis/src/docsys/build/main.xsl
> +                  is moving to <a href="https://astrogeology.usgs.gov/docs/" target="_blank">USGS Astrogeology Software Docs</a>.
There should be some mention that the manuals are still here (not just docs for past ISIS versions), although I can put the other part at the front.

The first version is repetitive. Essentially, tutorials and how-to guides are the same thing. Guides and usage explanations are also the same thing.  Is there anything missing if I just say "tutorials and guides", or maybe "ISIS tutorials, guides, and concepts"?  Both are more concise and sound better imo.

Is this any better?

> ISIS documentation, including ISIS tutorials, guides, and concepts,
> have been moved to **USGS Astrogeology Software Docs**.
> Manuals for each ISIS Application **remain here**, as do docs
> for previous ISIS versions, accessible via the left panel.

2024-11-25 20:14 UTC, jrcain-usgs commented on isis/src/docsys/build/main.xsl
> +                  is moving to <a href="https://astrogeology.usgs.gov/docs/" target="_blank">USGS Astrogeology Software Docs</a>.
I'm changing the name of the site from "ISIS Documentation" to "ISIS Application Manuals", since the manuals are all that will be here going forward.

2024-11-26 15:51 UTC, Kelvinrr commented on isis/src/docsys/build/main.xsl
> +                  is moving to <a href="https://astrogeology.usgs.gov/docs/" target="_blank">USGS Astrogeology Software Docs</a>.
Tutorials and how-to guides are not the same thing, [we explicitly separate them in our docs](https://astrogeology.usgs.gov/docs/), so I don't agree it was repetitive. 

I think the new one you linked here is good. 

Can you update the description with a screenshot of that the site looks like, it'll save some time for reviewers when it comes to these doc updates.

2025-01-03 20:30 UTC, Kelvinrr approved these changes

2025-01-03 20:30 UTC, merged