Add Longitude gtest unit test
DOI-USGS/ISIS3 pull request #601
Opened 2018-11-20 22:08 UTC by chrisryancombs

2018-11-20 22:59 UTC, kberryUSGS commented on isis/src/base/objs/Longitude/LongitudeTests.cpp
> +
Very minor comment, but could you remove all this whitespace?

2018-11-20 23:24 UTC, kaitlyndlee commented on isis/src/base/objs/Longitude/LongitudeTests.cpp
> +  Longitude lon(180.0, Angle::Degrees, Longitude::PositiveWest);
Should we also check to see what the methods positiveWest() and positiveEast() return?

2018-11-20 23:25 UTC, kaitlyndlee commented on isis/src/base/objs/Longitude/LongitudeTests.cpp
> +
Do we need to test the other two constructors?

2018-11-20 23:28 UTC, kaitlyndlee commented on isis/src/base/objs/Longitude/LongitudeTests.cpp
> +  EXPECT_EQ(90, lon.degrees());
Should we also check to see what positiveEast() returns?

2018-11-20 23:29 UTC, kdl222 commented on isis/src/base/objs/Longitude/LongitudeTests.cpp
> +  EXPECT_EQ(270, lon.degrees());
Should we also check to see what positiveWest() returns?

2018-11-20 23:30 UTC, kdl222 commented on isis/src/base/objs/Longitude/LongitudeTests.cpp
> +  lonCopy = lon;
Should this be in its own test?

2018-11-20 23:39 UTC, kberryUSGS commented
@chrisryancombs Could you put the old unit test and truthdata back in? We're leaving them in for now.

2018-11-21 17:37 UTC, krlberry requested changes
@chrisryancombs Could you put the old unit test and truthdata back in? We're leaving them in for now.

2018-11-30 17:30 UTC, Kelvinrr commented
Can one of the admins verify this patch?

2018-12-01 19:20 UTC, jlaura commented
@chrisryancombs Can you update this for the comments from @kberryUSGS and then change the target branch to `dev`?

2019-03-27 16:38 UTC, jessemapel commented
As Ryan has left, continued at #3182

2019-03-27 16:38 UTC, closed without merging