Added stitched frame projection cattest to tgo.
DOI-USGS/ISIS3 pull request #61
Opened 2018-02-08 18:15 UTC by AgoinsUSGS

2018-02-08 22:53 UTC, krlberry requested changes

2018-02-08 22:53 UTC, kberryUSGS commented on isis/src/tgo/tsts/projSingleStichedFrame/Makefile
> +            outputprefix=$(OUTPUT)/"Narwahl" > /dev/null;
Could you change the output prefix to something that describes the generated cube? In the case of future test failures, having a descriptive cube name will help to more quickly determine the problem.

2018-02-09 21:18 UTC, AgoinsUSGS commented
Changes have been implemented!

2018-02-12 16:07 UTC, krlberry approved these changes
:+1: Thanks!

2018-02-12 20:48 UTC, merged