Fix libtiff dependency (#636)
DOI-USGS/ISIS3 pull request #644
Opened 2018-12-14 19:15 UTC by seignovert

## Description
Update `libtiff` dependency to `>=4.0.10` to fix conda installation fails on Linux systems (#636).

The previous `libtiff` were using single digit build number. Now there are prefixed with `he6b73bb_`:
```
$ conda search libtiff
Loading channels: done
# Name                  Version           Build  Channel             
libtiff                   4.0.7               0  conda-forge         
libtiff                   4.0.7               1  conda-forge
libtiff                   4.0.8               0  conda-forge
libtiff                   4.0.9      he6b73bb_1  conda-forge         
libtiff                   4.0.9      he6b73bb_2  conda-forge         
libtiff                  4.0.10      he6b73bb_0  conda-forge         
libtiff                  4.0.10      he6b73bb_1  conda-forge
```

## Related Issue
Issue: #636

2018-12-14 21:31 UTC, jessemapel commented
I get the following error when I try to create our build environment with this change:

```
jmapel$ conda env create -f environment.yml -n isis3_libtiff
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - geotiff==1.4.2=1 -> libtiff[version='>=4.0.8,<4.0.10']
  - libtiff[version='>=4.0.10']
```

I'm going to try setting `>=4.0.9` Ideally we can just remove the version number but that will require more testing than I have time for at the moment.

2018-12-14 22:47 UTC, jessemapel requested changes
Using 4.0.10 or higher causes a conflict with geotiff.

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - geotiff==1.4.2=1 -> libtiff[version='>=4.0.8,<4.0.10']
  - libtiff[version='>=4.0.10']
Use "conda info <package>" to see the dependencies for each package.
```

2018-12-14 22:54 UTC, jessemapel commented
I've tested with setting 4.0.9 or higher and I'm able to build and work with tiff images

2018-12-17 17:15 UTC, jessemapel approved these changes

2018-12-17 17:18 UTC, merged

2018-12-17 17:40 UTC, scsides reviewed
This should not be a problem

2018-12-18 01:04 UTC, jlaura commented
@scsides Can you expand on what you are referring to?