Adds Issue Templates to Issues
DOI-USGS/ISIS3 pull request #664
Opened 2018-12-19 16:10 UTC by jlaura

## Description

PR adds four issue templates for helping to categorize issues. This PR makes a distinction between bugs and features to assist in watching version numbers.

## Related Issue

#661 
## Motivation and Context

We are seeking to provide additional support to contributors opening issues.

## How Has This Been Tested?

No testing is required as this is not a code change.
## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2018-12-19 19:02 UTC, jessemapel submitted a review, later dismissed
Looks good to me, I'd like another set of eyes to check it before we merge this.

2018-12-19 20:02 UTC, SgStapleton requested changes

2018-12-19 20:02 UTC, SgStapleton commented on .github/ISSUE_TEMPLATE/3_Support_question.md
> +this kind of questions about using ISIS3 or other ASC software, please use
"For questions about using ISIS3 or other ASC software, ..."

2018-12-19 20:02 UTC, SgStapleton commented on .github/ISSUE_TEMPLATE/3_Support_question.md
> +this kind of questions about using ISIS3 or other ASC software, please use
Or something of the like. Not entirely sure what was meant here.

2018-12-21 19:06 UTC, jlaura commented
@SgStapleton Does this look okay? If so, lets wait to merge until discourse is live. Then we can flip the switch.

@scsides Do you know if issue templates will interfere with the migration?

2018-12-21 20:30 UTC, scsides commented
I have no idea at this point.

2018-12-21 20:38 UTC, jessemapel commented
@jlaura @scsides Can we merge this and then if they are an issue for the transition, disable them until that is done?

2018-12-21 20:41 UTC, jlaura commented
@jessemapel Sure on the RedMine side. It looks like we are almost live on astrodiscuss.usgs.gov. I would like to wait for that to go live since the question templates asks users to use that. I do not want to have questions from contributors in limbo.

2018-12-21 21:29 UTC, SgStapleton approved these changes

2019-02-02 22:02 UTC, jlaura commented
@all safe to merge?

2019-02-06 19:08 UTC, jlaura commented
Once #690 is merged, we should be able to merge this.

2019-03-02 16:51 UTC, merged