Added colored mosaic cat test to tgo
DOI-USGS/ISIS3 pull request #85
Opened 2018-02-22 22:21 UTC by AgoinsUSGS

Truthdata for this cat test is located in: /work/users/agoins/TGO_TRUTHDATA/coloredMos

2018-02-23 18:19 UTC, jessemapel requested changes

2018-02-23 18:19 UTC, jessemapel commented on isis/src/tgo/tsts/coloredMosaic/Makefile
> +					 to=$(OUTPUT)/$\$$\1.cub -batchlist=$(OUTPUT)/panBasenames.lis > /dev/null;
Spacing is all over the place across this makefile. It's probably your editor doing things you don't expect. Really egregious things like this line should be cleaned up.

2018-02-23 18:19 UTC, jessemapel commented on isis/src/tgo/tsts/coloredMosaic/Makefile
> +	$(EXPORT) $(TSTSARGS) from=$(OUTPUT)/panCassisMosaic.cub to=$(OUTPUT)/panCassisMosaic  \
This test shouldn't worry about exporting single color mosaics. It should only export the final color mosaic

2018-02-23 18:19 UTC, jessemapel commented on isis/src/tgo/tsts/coloredMosaic/Makefile
> +
Make sure you clean up the output `coloredMosaic.xml` file.

2018-02-27 00:04 UTC, AgoinsUSGS commented
Changes have been implemented

2018-02-27 17:58 UTC, jessemapel commented on isis/src/tgo/tsts/coloredMosaic/Makefile
> +	$(RM) $(OUTPUT)/coloredMosaic.xml;
Don't remove the output IMG and XML files.  The XML file will need to be modified to remove some things and renamed to a TXT file.

2018-03-12 23:05 UTC, jessemapel commented
Couple more changes. See the changes on my branch:

https://github.com/AgoinsUSGS/ISIS3/compare/coloredmos...jessemapel:colormosaic

Also, I'm getting slightly different mosaic extents when I run it locally.  See `/work/users/jmapel/ISIS3/isis/src/tgo/tsts/coloredMosaic` and compare the output to the truth data.

2018-03-17 00:08 UTC, jessemapel submitted a review, later dismissed

2018-03-17 00:24 UTC, jessemapel approved these changes

2018-03-17 00:32 UTC, merged